# Generated by Django 4.2.5 on 2023-09-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_reuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reuser',
        ),
    ]
