# Generated by Django 4.2.5 on 2023-09-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_userprofile_delete_reuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Fdate', models.DateField()),
                ('Tdata', models.DateField()),
                ('Reasion', models.CharField(max_length=100)),
            ],
        ),
    ]
