# Generated by Django 4.2.5 on 2023-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0007_alter_leave_fdate_alter_leave_tdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='Grant',
            field=models.CharField(default='not grant', max_length=20),
        ),
    ]
